### ISSUE TITLE
Getting the min_tag_id information from tag_recent_media api call

### ISSUE THREAD

**Issue by k4v1r4j** [Instagram/python-instagram#120]
currently tag_recent_media returns a tuple (media, next). The returned information contains no information about min_tag_id. Say I need to keep track of latest posts using min_tag_id. How will I get the recent min_tag_id every time I get tag_recent_media. I think that's a good idea to return that information as well.

**Comment by tchapi** [comment]
+1 !

**Comment by k4v1r4j** [comment]
So. What are we going to do about it??

**Comment by k4v1r4j** [comment]
Hi Guys, We can get the min_tag_id info using paramter "pagination_format" as "dict".

say, api.get_tag_recent_media(tag_name='fun', pagination_format='dict')

Response would be Something like

  Media: 248444491128559992_596973,
  Media: 257832753228077087_596973,
  Media: 267421445672327437_596973,
  Media: 274168292348713609_596973],
 {'deprecation_warning': 'next_max_id and min_id are deprecated for this endpoint; use min_tag_id and max_tag_id instead',
  'min_tag_id': '1425287407627242',
  'next_max_id': '1423757044940776',
  'next_max_tag_id': '1423757044940776',
  'next_min_id': '1425287407627242',
  'next_url': 'https://api.instagram.com/v1/tags/thealbums/media/recent?client_id=<client_id>&max_tag_id=1423757044940776'})


And we got min_tag_id.. :) Thats so cool. I figured it out by going through source code.
