### ISSUE TITLE
media_shortcode always raise a 404 error

### ISSUE THREAD

**Issue by Badrane** [Instagram/python-instagram#127]
While the method *media_shortcode* is performed a ".json" is added to the request made to the API which then always returns a 404 error.

**Comment by dtran320** [comment]
@heatonjb Thanks for merging in #150. Do you have any feedback on this or #135?

**Comment by dtran320** [comment]
@Badrane I believe this issue can be closed now that #135 is merged in. Thanks @heatonjb!

**Comment by Badrane** [comment]
@dtran320 @heatonjb Thank you guys!
