### ISSUE TITLE
tag_recent_media parameters

### ISSUE THREAD

**Issue by macdonjo** [Instagram/python-instagram#136]
api.tag_recent_media(count, max_tag_id, tag_name)

The count is always limited at 33 on every call.

max_tag_id has no effect.

Has anyone had a similar experience?

**Comment by k4v1r4j** [comment]
I have been using tag_recent_media and found no such problems yet. Can you tell more about on the exact request you made and response you have got?

**Comment by georgewhewell** [comment]
I also see this.

```
import os
from instagram.client import InstagramAPI

api = InstagramAPI(access_token=os.environ.get('ACCESS_TOKEN'))

for count in [30, 33, 40]:
    media, next_url = api.tag_recent_media(
        count=count, tag_name="test")
    print('Asked for {}, got {}'.format(count, len(media)))

## 
# ACCESS_TOKEN=... python test.py
# Asked for 30, got 30
# Asked for 33, got 33
# Asked for 40, got 33
##
```

**Comment by kavirajk** [comment]
@georgewhewell tag_recent_media sends max of 33 media per request. You have to use next_url if you want more media

**Comment by DataNeel** [comment]
@kavirajk How is the next_url used? Unlike user_recent_media, the tag_recent_media method doesn't seem to take a next url as an argument.
