### ISSUE TITLE
user_search docs are wrong

### ISSUE THREAD

**Issue by ifnull** [Instagram/python-instagram#162]
api.user_search has no lat/lon params. See line 123 of README.md

**Comment by heatonjb** [comment]
line 123: recent_media, next_ = api.user_recent_media()

**Comment by dellsystem** [comment]
I believe the line number is now [145](https://github.com/Instagram/python-instagram/blame/master/README.md#L145) now, and the line looks like this:

```python
api.user_search(q, count, lat, lng, min_timestamp, max_timestamp)
```

I came here to post the same thing. Here's a link to the line in the most recent commit in case it gets changed: https://github.com/Instagram/python-instagram/blame/dfeebe91cf389017e1786bd153d3d1285406ee9e/README.md#L145
