### ISSUE TITLE
Force login

### ISSUE THREAD

**Issue by ShriramK** [Instagram/python-instagram#185]
Hello
During authentication I don't see the skip or deny option besides allow.
I do see classic force login in the authentication url in the browser. That could be the reason option's not seen.
Is there way to enable deny or cancel option as well ?
Thanks

**Comment by nuvipannu** [comment]
It's not possible. Instagram does not allow you to do that. :sob: 
http://stackoverflow.com/q/24550048

**Comment by ShriramK** [comment]
I see. Thanks @nuvipannu
