### ISSUE TITLE
How to get the user id by name

### ISSUE THREAD

**Issue by csselo** [Instagram/python-instagram#194]
Hi

is there any method to get the user id?

thanks

**Comment by csselo** [comment]
Hi

I want to get the user follower ids but it shows only name
https://instagram.com/developer/endpoints/relationships/
normally it must show all infos

**Comment by csselo** [comment]
solved 
User.id :)

**Comment by PaulMest** [comment]
@csselo Please close your issue if there is no action required by the team that maintains this project.
